#!/bin/bash

while getopts ":t:" opt; do
	case "$opt" in
		t)
			tag=$OPTARG
			;;
	esac
done

tag=$(printf "%10s" $tag)

while IFS= read -r line; do
	timestamp=$(date '+%d-%m-%Y %H:%M:%S')
	line=$(sed 's/[a-z]*\[[0-9]*\]: //' <<< $line)
	echo "$timestamp    $tag    $line" >> /var/log/services
done
