alias ls='ls --color --human-readable --group-directories-first'
alias grep='grep --color'
alias diff='diff --color'

export EDITOR=nvim
export LESSHISTFILE=-
export PS1='\[\e[38;5;196m\]\w \[\e[38;5;45m\]\$ \[\e[0m\]'
