#!/bin/sh

# Edit root files with nvim running as a normal user.

if [ $# -eq 0 -o -z "$1" ]; then
	echo "usage: ${0##*/} [FILE]"
	exit 1
fi

if [ $(whoami) = "root" ]; then
	file=$1
	tmpdir=$(mktemp -d /tmp/svim-XXXXXXXXXX) # Copy to dir to preserve file name
	tmpfile=$tmpdir/${file##*/}

	[ -e $file ] || touch $file
	ownership=$(stat -c "%u:%g" $file)
	cp --preserve=mode,timestamps $file $tmpfile

	chown $SVIM_USER $tmpdir $tmpfile
	su $SVIM_USER -c "nvim $tmpfile"
	
	mv $tmpfile $file
	chown $ownership $file
	rmdir $tmpdir
else
	export SVIM_USER=$(whoami)
	exec doas $0 $1
fi
